language: python
python:
  - "2.7"
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install python-coveralls
  - pip install -r requirements.txt
  - mount
  - curl https://raw.githubusercontent.com/cglewis/travis-docker/master/strap | source /dev/stdin
script:
  - docker ps
  - py.test -v --cov bowl --cov-report term-missing
after_success:
  - coveralls
branches:
  except:
  - gh-pages
notifications:
  email:
    - charlie.lewis42@gmail.com
