FROM ubuntu:precise

MAINTAINER Charlie Lewis

RUN apt-get update && apt-get install -y \
    git \
    libxml2-dev \
    python \
    build-essential \
    make \
    gcc \
    python-dev \
    locales \
    python-pip

CMD python
